version: 2.1

jobs:
  one:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "This is job one"

  two:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "This is job two"

workflows:
  one_and_two:
    jobs:
      - one
      - two
