version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    executor:
      name: node/default
      tags: '10.4'
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run test
